# Generated by Django 5.1.1 on 2024-10-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_on_vacations",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
